.github/workflows/update-chalk-private.yml
- dispatch to chalk-private
- minimum perms
- yes newline
- update token
- add read perms for action
=> Add perms for action

fraud-2.mdx, has-many.mdx, has-one.mdx
=> new has one has many syntax

debugging-errors.mdx, debugging.mdx, faq.mdx
based on all customer questions over past 3 months
=> faqs and debugging

runs.mdx
Add descriptions of the additional parameters that are available on the trigger resolver api endpoint, so that this page can be linked from the dashboard resolver trigger form.
=> Update resolver trigger api documentation

changelog.mdx
It'll be easier to get a sense of what's shipped!
=> add table of contents to changelog

changelog.mdx, training-client.mdx
Might be easier to review by commit
=> Document spine_sql_query in prose docs

aggregations.mdx, setup-guide.mdx
1. The setup guide had some steps that weren't showing up separately due to the line breaks
2. Cleaned up some typos in the aggregations docs
=> Docs polish

aggregations.mdx, windowed-streaming.mdx
First pass at splitting out these docs so that we can add more information about materialization and grouping in followup commits
(I know I need to update the nav bar in chalk-private for the new file)
=> split windowed features and information about streaming

aggregations.mdx
Elliot reviewed in gdocs already
=> Add materialization docs

best-practices.mdx
Explain chalk.yaml and requirements.txt
=> Update best practices

aggregations.mdx
=> add chalk_window docs

backfilling-data.mdx, benchmarks.mdx, best-practices.mdx, changelog.mdx, dataframe.mdx, editor-setup.mdx, embeddings.mdx, faq.mdx, fraud-tutorial.mdx, has-many.mdx, has-one.mdx, notebook-tutorial.mdx, query-online.mdx, query-overview.mdx, resolver-inputs.mdx, resolver-outputs.mdx, resolver-overview.mdx, setup-guide.mdx, sql.mdx, time.mdx, vector-search.mdx, window-functions.mdx
=> no more feature set language

query-overview.mdx, scheduled-query.mdx
could param typos in code examples
=> (fix): param typo ofq

snapshot-tests.mdx
Adds a docs page on snapshot testing
=> (feat): short short doc on snapshot testing

changelog.mdx
Fixed whitespace and line endings in changelog.mdx
This PR removes trailing whitespace and normalizes line endings throughout the changelog document, improving consistency and readability.
=> feat: Add cloud resource configuration advanced settings

changelog.mdx
Added January 2025 product updates including:
- KEDA implementation for dynamic resource scaling and cost optimization
- CLI commands for viewing logs and exporting metrics
- Graph view for visualizing feature data lineage and connections
These improvements enhance resource efficiency, expand CLI capabilities, and provide better feature visualization tools.
=> feat: Add KEDA scaling, CLI logs/metrics, and graph view features

changelog.mdx
Added January 15th, 2025 release notes highlighting:
- Added SQL table query support for online queries with optimization capabilities
- Introduced feature value metrics in the dashboard for deployment debugging
- Extended microservice build caching for faster, parallel rollbacks
- Improved branch querying performance through optimized compute sharing
These updates focus on improving operational efficiency, query capabilities, observability, and deployment flexibility.
=> feat: Improve billing, SQL queries, metrics, rollbacks and branch performance

changelog.mdx
Added Spanner DB support, composite keys, and enhanced deployment visibility
This release introduces three major improvements:
1. Added formal Spanner DB support to Chalk's C++ SQL driver, reducing query latencies from 24ms to 10ms
2. Introduced composite key support with Chalk expressions, enabling:
- Basic resolvers
- Parent-child relationships
- DataFrame resolvers
- Automatic key computation for single-key stores
3. Enhanced deployment visibility features:
- Color-coded SQL resolver and Chalk expression nodes in query plan viewer
- Added Kubernetes events API data to resource page
- Fixed breadcrumb hyperlinking in query plan viewer
=> changelog 2025-01-22

changelog.mdx
Added hyperlinks to documentation and improved query plan viewer navigation
This update enhances documentation clarity by adding hyperlinks to Spanner, Chalk expressions, and SQL resolvers documentation. The query plan viewer now includes breadcrumb navigation for easier feature lineage traversal. Performance improvements to the C++ SQL driver for Spanner have reduced query latencies from 24ms to 10ms.
The Kubernetes resource page now includes additional event data for better operational insights, covering node removal, pod scheduling, and deployment failures.
=> feat: Add C++ SQL inputs, query plan viewer updates, and K8s events

what-is-chalk.mdx
=> (fix): what is chalk example

notebook-development.mdx, notebook-setup.mdx
Update docs for notebook dev with latest best approach
=> (feat): update docs on notebook dev to reflect best approach

notebook-development.mdx, notebook-setup.mdx
small fixes (and re-add notebook setup page)
=> (fix): update notebook setup

notebook-setup.mdx
=> fix broken notebook links

prompts.mdx
=> docs for prompts

gcp-cloud-deployment.mdx
add setLabels for global addresses in GCP
=> add setLabels for global addresses in GCP

changelog.mdx
=> feat: Changelog 2025-06-06

architecture.mdx
feat: rewrote platform architecture docs to be more clear and shed light on Velox, data orchestration, alerting, and interop
=> Rewrote platform architecture docs

alertconfig.mdx, incidentio.mdx, observability.mdx
Adds a short summary of how to integrate IncidentIo
=> Added short doc on IncidentIo Integration

incidentio.mdx
Updated IncidentIo docs to reflect change from incidents to alerts.
=> Updated IncidentIo docs

incidentio.mdx
Fixed Formatting on IncidentIo Page
=> Fixed Formatting on IncidentIo Page

best-practices.mdx, named-query.mdx
- do not merge before https://github.com/chalk-ai/chalk-private/pull/23426
=> updated named query docs to mention offline querying

development-with-llms.mdx
=> Creating Developing with LLM docs

vector-search.mdx
=> Update vector-search doc
